// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MudBlazorApp.DataContext;

#nullable disable

namespace MudBlazorApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240615234328_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MudBlazorApp.Entities.Departamento", b =>
                {
                    b.Property<int>("DepartamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartamentoId"));

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DepartamentoId");

                    b.ToTable("Departamentos");

                    b.HasData(
                        new
                        {
                            DepartamentoId = 1,
                            Nome = "Gestão"
                        },
                        new
                        {
                            DepartamentoId = 2,
                            Nome = "Desenvolvimento"
                        },
                        new
                        {
                            DepartamentoId = 3,
                            Nome = "Infraestrutura"
                        },
                        new
                        {
                            DepartamentoId = 4,
                            Nome = "Qualidade"
                        },
                        new
                        {
                            DepartamentoId = 5,
                            Nome = "Suporte"
                        });
                });

            modelBuilder.Entity("MudBlazorApp.Entities.DespesaMensal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<int>("MesReferencia")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("DespesaMensais");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartamentoId = 1,
                            MesReferencia = 1,
                            Valor = 150000m
                        },
                        new
                        {
                            Id = 2,
                            DepartamentoId = 1,
                            MesReferencia = 2,
                            Valor = 145000m
                        },
                        new
                        {
                            Id = 3,
                            DepartamentoId = 1,
                            MesReferencia = 3,
                            Valor = 155000m
                        },
                        new
                        {
                            Id = 4,
                            DepartamentoId = 1,
                            MesReferencia = 4,
                            Valor = 160000m
                        },
                        new
                        {
                            Id = 5,
                            DepartamentoId = 1,
                            MesReferencia = 5,
                            Valor = 165000m
                        },
                        new
                        {
                            Id = 6,
                            DepartamentoId = 1,
                            MesReferencia = 6,
                            Valor = 170000m
                        },
                        new
                        {
                            Id = 7,
                            DepartamentoId = 1,
                            MesReferencia = 7,
                            Valor = 175000m
                        },
                        new
                        {
                            Id = 8,
                            DepartamentoId = 1,
                            MesReferencia = 8,
                            Valor = 180000m
                        },
                        new
                        {
                            Id = 9,
                            DepartamentoId = 1,
                            MesReferencia = 9,
                            Valor = 185000m
                        },
                        new
                        {
                            Id = 10,
                            DepartamentoId = 1,
                            MesReferencia = 10,
                            Valor = 190000m
                        },
                        new
                        {
                            Id = 11,
                            DepartamentoId = 1,
                            MesReferencia = 11,
                            Valor = 195000m
                        },
                        new
                        {
                            Id = 12,
                            DepartamentoId = 1,
                            MesReferencia = 12,
                            Valor = 200000m
                        },
                        new
                        {
                            Id = 13,
                            DepartamentoId = 2,
                            MesReferencia = 1,
                            Valor = 120000m
                        },
                        new
                        {
                            Id = 14,
                            DepartamentoId = 2,
                            MesReferencia = 2,
                            Valor = 118000m
                        },
                        new
                        {
                            Id = 15,
                            DepartamentoId = 2,
                            MesReferencia = 3,
                            Valor = 122000m
                        },
                        new
                        {
                            Id = 16,
                            DepartamentoId = 2,
                            MesReferencia = 4,
                            Valor = 125000m
                        },
                        new
                        {
                            Id = 17,
                            DepartamentoId = 2,
                            MesReferencia = 5,
                            Valor = 128000m
                        },
                        new
                        {
                            Id = 18,
                            DepartamentoId = 2,
                            MesReferencia = 6,
                            Valor = 130000m
                        },
                        new
                        {
                            Id = 19,
                            DepartamentoId = 2,
                            MesReferencia = 7,
                            Valor = 132000m
                        },
                        new
                        {
                            Id = 20,
                            DepartamentoId = 2,
                            MesReferencia = 8,
                            Valor = 135000m
                        },
                        new
                        {
                            Id = 21,
                            DepartamentoId = 2,
                            MesReferencia = 9,
                            Valor = 138000m
                        },
                        new
                        {
                            Id = 22,
                            DepartamentoId = 2,
                            MesReferencia = 10,
                            Valor = 140000m
                        },
                        new
                        {
                            Id = 23,
                            DepartamentoId = 2,
                            MesReferencia = 11,
                            Valor = 142000m
                        },
                        new
                        {
                            Id = 24,
                            DepartamentoId = 2,
                            MesReferencia = 12,
                            Valor = 145000m
                        },
                        new
                        {
                            Id = 25,
                            DepartamentoId = 3,
                            MesReferencia = 1,
                            Valor = 90000m
                        },
                        new
                        {
                            Id = 26,
                            DepartamentoId = 3,
                            MesReferencia = 2,
                            Valor = 88000m
                        },
                        new
                        {
                            Id = 27,
                            DepartamentoId = 3,
                            MesReferencia = 3,
                            Valor = 91000m
                        },
                        new
                        {
                            Id = 28,
                            DepartamentoId = 3,
                            MesReferencia = 4,
                            Valor = 93000m
                        },
                        new
                        {
                            Id = 29,
                            DepartamentoId = 3,
                            MesReferencia = 5,
                            Valor = 95000m
                        },
                        new
                        {
                            Id = 30,
                            DepartamentoId = 3,
                            MesReferencia = 6,
                            Valor = 97000m
                        },
                        new
                        {
                            Id = 31,
                            DepartamentoId = 3,
                            MesReferencia = 7,
                            Valor = 99000m
                        },
                        new
                        {
                            Id = 32,
                            DepartamentoId = 3,
                            MesReferencia = 8,
                            Valor = 100000m
                        },
                        new
                        {
                            Id = 33,
                            DepartamentoId = 3,
                            MesReferencia = 9,
                            Valor = 102000m
                        },
                        new
                        {
                            Id = 34,
                            DepartamentoId = 3,
                            MesReferencia = 10,
                            Valor = 104000m
                        },
                        new
                        {
                            Id = 35,
                            DepartamentoId = 3,
                            MesReferencia = 11,
                            Valor = 106000m
                        },
                        new
                        {
                            Id = 36,
                            DepartamentoId = 3,
                            MesReferencia = 12,
                            Valor = 108000m
                        },
                        new
                        {
                            Id = 37,
                            DepartamentoId = 4,
                            MesReferencia = 1,
                            Valor = 60000m
                        },
                        new
                        {
                            Id = 38,
                            DepartamentoId = 4,
                            MesReferencia = 2,
                            Valor = 59000m
                        },
                        new
                        {
                            Id = 39,
                            DepartamentoId = 4,
                            MesReferencia = 3,
                            Valor = 61000m
                        },
                        new
                        {
                            Id = 40,
                            DepartamentoId = 4,
                            MesReferencia = 4,
                            Valor = 62000m
                        },
                        new
                        {
                            Id = 41,
                            DepartamentoId = 4,
                            MesReferencia = 5,
                            Valor = 63000m
                        },
                        new
                        {
                            Id = 42,
                            DepartamentoId = 4,
                            MesReferencia = 6,
                            Valor = 64000m
                        },
                        new
                        {
                            Id = 43,
                            DepartamentoId = 4,
                            MesReferencia = 7,
                            Valor = 65000m
                        },
                        new
                        {
                            Id = 44,
                            DepartamentoId = 4,
                            MesReferencia = 8,
                            Valor = 66000m
                        },
                        new
                        {
                            Id = 45,
                            DepartamentoId = 4,
                            MesReferencia = 9,
                            Valor = 67000m
                        },
                        new
                        {
                            Id = 46,
                            DepartamentoId = 4,
                            MesReferencia = 10,
                            Valor = 68000m
                        },
                        new
                        {
                            Id = 47,
                            DepartamentoId = 4,
                            MesReferencia = 11,
                            Valor = 69000m
                        },
                        new
                        {
                            Id = 48,
                            DepartamentoId = 4,
                            MesReferencia = 12,
                            Valor = 70000m
                        },
                        new
                        {
                            Id = 49,
                            DepartamentoId = 5,
                            MesReferencia = 1,
                            Valor = 75000m
                        },
                        new
                        {
                            Id = 50,
                            DepartamentoId = 5,
                            MesReferencia = 2,
                            Valor = 74000m
                        },
                        new
                        {
                            Id = 51,
                            DepartamentoId = 5,
                            MesReferencia = 3,
                            Valor = 76000m
                        },
                        new
                        {
                            Id = 52,
                            DepartamentoId = 5,
                            MesReferencia = 4,
                            Valor = 77000m
                        },
                        new
                        {
                            Id = 53,
                            DepartamentoId = 5,
                            MesReferencia = 5,
                            Valor = 78000m
                        },
                        new
                        {
                            Id = 54,
                            DepartamentoId = 5,
                            MesReferencia = 6,
                            Valor = 79000m
                        },
                        new
                        {
                            Id = 55,
                            DepartamentoId = 5,
                            MesReferencia = 7,
                            Valor = 80000m
                        },
                        new
                        {
                            Id = 56,
                            DepartamentoId = 5,
                            MesReferencia = 8,
                            Valor = 81000m
                        },
                        new
                        {
                            Id = 57,
                            DepartamentoId = 5,
                            MesReferencia = 9,
                            Valor = 82000m
                        },
                        new
                        {
                            Id = 58,
                            DepartamentoId = 5,
                            MesReferencia = 10,
                            Valor = 83000m
                        },
                        new
                        {
                            Id = 59,
                            DepartamentoId = 5,
                            MesReferencia = 11,
                            Valor = 84000m
                        },
                        new
                        {
                            Id = 60,
                            DepartamentoId = 5,
                            MesReferencia = 12,
                            Valor = 85000m
                        });
                });

            modelBuilder.Entity("MudBlazorApp.Entities.Funcionario", b =>
                {
                    b.Property<int>("FuncionarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FuncionarioId"));

                    b.Property<string>("Cargo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DataAdmissao")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("FuncionarioId");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Funcionarios");

                    b.HasData(
                        new
                        {
                            FuncionarioId = 1,
                            Cargo = "Gerente",
                            DataAdmissao = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartamentoId = 1,
                            Nome = "José",
                            Salario = 7000m
                        },
                        new
                        {
                            FuncionarioId = 2,
                            Cargo = "Coordenadora",
                            DataAdmissao = new DateTime(2018, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartamentoId = 1,
                            Nome = "Maria",
                            Salario = 6500m
                        },
                        new
                        {
                            FuncionarioId = 3,
                            Cargo = "Assistente Administrativo",
                            DataAdmissao = new DateTime(2022, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartamentoId = 1,
                            Nome = "Ricardo",
                            Salario = 2200m
                        },
                        new
                        {
                            FuncionarioId = 4,
                            Cargo = "Desenvolvedor Sênior",
                            DataAdmissao = new DateTime(2019, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartamentoId = 2,
                            Nome = "Carlos",
                            Salario = 3500m
                        },
                        new
                        {
                            FuncionarioId = 5,
                            Cargo = "Desenvolvedora Pleno",
                            DataAdmissao = new DateTime(2021, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartamentoId = 2,
                            Nome = "Ana",
                            Salario = 4200m
                        },
                        new
                        {
                            FuncionarioId = 6,
                            Cargo = "Desenvolvedor Júnior",
                            DataAdmissao = new DateTime(2023, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartamentoId = 2,
                            Nome = "Pedro",
                            Salario = 2500m
                        },
                        new
                        {
                            FuncionarioId = 7,
                            Cargo = "Estagiário de Desenvolvimento",
                            DataAdmissao = new DateTime(2023, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartamentoId = 2,
                            Nome = "Gabriel",
                            Salario = 1200m
                        },
                        new
                        {
                            FuncionarioId = 8,
                            Cargo = "Analista de Infraestrutura",
                            DataAdmissao = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartamentoId = 3,
                            Nome = "Rafael",
                            Salario = 4500m
                        },
                        new
                        {
                            FuncionarioId = 9,
                            Cargo = "Suporte Técnico",
                            DataAdmissao = new DateTime(2020, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartamentoId = 3,
                            Nome = "Fernanda",
                            Salario = 3200m
                        },
                        new
                        {
                            FuncionarioId = 10,
                            Cargo = "Estagiária de Infraestrutura",
                            DataAdmissao = new DateTime(2019, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartamentoId = 3,
                            Nome = "Bruna",
                            Salario = 1200m
                        },
                        new
                        {
                            FuncionarioId = 11,
                            Cargo = "Analista de Qualidade",
                            DataAdmissao = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartamentoId = 4,
                            Nome = "Carla",
                            Salario = 4000m
                        },
                        new
                        {
                            FuncionarioId = 12,
                            Cargo = "Técnico de Qualidade",
                            DataAdmissao = new DateTime(2020, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartamentoId = 4,
                            Nome = "Paulo",
                            Salario = 3200m
                        },
                        new
                        {
                            FuncionarioId = 13,
                            Cargo = "Analista de Suporte",
                            DataAdmissao = new DateTime(2019, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartamentoId = 5,
                            Nome = "João",
                            Salario = 3800m
                        },
                        new
                        {
                            FuncionarioId = 14,
                            Cargo = "Técnica de Suporte",
                            DataAdmissao = new DateTime(2018, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartamentoId = 5,
                            Nome = "Mariana",
                            Salario = 3000m
                        },
                        new
                        {
                            FuncionarioId = 15,
                            Cargo = "Assistente de Suporte",
                            DataAdmissao = new DateTime(2020, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartamentoId = 5,
                            Nome = "Lucas",
                            Salario = 2500m
                        },
                        new
                        {
                            FuncionarioId = 16,
                            Cargo = "Analista Financeiro",
                            DataAdmissao = new DateTime(2018, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartamentoId = 1,
                            Nome = "Eduardo",
                            Salario = 6000m
                        },
                        new
                        {
                            FuncionarioId = 17,
                            Cargo = "Desenvolvedora Júnior",
                            DataAdmissao = new DateTime(2018, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartamentoId = 2,
                            Nome = "Amanda",
                            Salario = 2800m
                        },
                        new
                        {
                            FuncionarioId = 18,
                            Cargo = "Analista de Marketing",
                            DataAdmissao = new DateTime(2019, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartamentoId = 3,
                            Nome = "Carolina",
                            Salario = 5000m
                        },
                        new
                        {
                            FuncionarioId = 19,
                            Cargo = "Assistente Administrativo",
                            DataAdmissao = new DateTime(2020, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartamentoId = 4,
                            Nome = "Roberto",
                            Salario = 2300m
                        },
                        new
                        {
                            FuncionarioId = 20,
                            Cargo = "Suporte Técnico",
                            DataAdmissao = new DateTime(2021, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartamentoId = 5,
                            Nome = "Rodrigo",
                            Salario = 3100m
                        },
                        new
                        {
                            FuncionarioId = 21,
                            Cargo = "Analista de Vendas",
                            DataAdmissao = new DateTime(2022, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartamentoId = 1,
                            Nome = "Isabela",
                            Salario = 4800m
                        });
                });

            modelBuilder.Entity("MudBlazorApp.Entities.DespesaMensal", b =>
                {
                    b.HasOne("MudBlazorApp.Entities.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("MudBlazorApp.Entities.Funcionario", b =>
                {
                    b.HasOne("MudBlazorApp.Entities.Departamento", "Departamento")
                        .WithMany("Funcionarios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("MudBlazorApp.Entities.Departamento", b =>
                {
                    b.Navigation("Funcionarios");
                });
#pragma warning restore 612, 618
        }
    }
}
